name: Coverage Pipeline

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit test Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Run unit test coverage
        run: make coverage/unit

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: coverage/*
          if-no-files-found: error
          retention-days: 1

  e2e:
    name: E2E test coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ubuntu-22.04

      - name: Run e2e test coverage
        run: make coverage/e2e
        env:
          E2E_TEST_CIFUZZ_API_TOKEN: ${{ secrets.E2E_TEST_CIFUZZ_API_TOKEN }}

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: coverage/*
          if-no-files-found: error
          retention-days: 1

  integration:
    name: Integration test coverage
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ubuntu-22.04

      - name: Run integration test coverage
        run: make coverage/integration

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: coverage/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge Coverage + Report
    runs-on: ubuntu-22.04
    needs: [integration, e2e, unit]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data
          path: coverage

      - name: Merge data and generate report
        run: make coverage/merge

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: coverage/report.html
          if-no-files-found: error
          retention-days: 5

  all:
    name: Catch all coverage report
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ubuntu-22.04

      - name: Test Coverage
        run: make coverage
