name: Release E2E testing

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  e2e:
    name: E2E / Behavior tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
      fail-fast: false # We care about results from other pipelines

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install cifuzz
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/adombeck/cifuzz/main/install.sh)"
        shell: sh

      # "$HOME/cifuzz/bin" can be removed as soon as new install path is released
      - name: Update Path - MacOS/Linux
        if: contains(matrix.os, 'macos')
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        shell: bash

      - name: Update Path - Windows
        if: contains(matrix.os, 'windows')
        # Windows can't find cifuzz executable without this
        # https://www.scivision.dev/github-actions-path-append/
        run: |
          echo "${HOME}/AppData/Roaming/cifuzz/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Run e2e tests matrix
        run: make test/e2e-use-installed-cifuzz
        env:
          E2E_TEST_CIFUZZ_API_TOKEN: ${{ secrets.E2E_TEST_CIFUZZ_API_TOKEN }}

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log-${{ matrix.os }}
          path: gotest.log
          if-no-files-found: error
