# This name is used in other pipelines that run afterwards
# Be careful when changing it
name: Release Pipeline

on:
  schedule:
    - cron: "0 7 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Create Version and Release notes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
      tag: ${{ steps.semantic.outputs.new_release_git_tag }}
      notes: ${{ steps.semantic.outputs.new_release_notes }}
      published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  installer:
    name: Build installer
    uses: ./.github/workflows/workflow_installer.yml
    needs: version
    if: needs.version.outputs.published == 'true'
    permissions:
      actions: write # for uploading artifacts
    with:
      version: ${{ needs.version.outputs.version }}
      compatibility_check: ${{ vars.RELEASE_COMPATIBILITY_CHECK }}

  tag_container_image:
    name: Tag container image
    needs: [version, installer]
    if: needs.version.outputs.published == 'true'
    uses: ./.github/workflows/workflow_container_image.yml
    with:
      version: ${{ needs.version.outputs.version }}

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [version, installer, tag_container_image]
    if: needs.version.outputs.published == 'true'
    permissions:
      contents: write # for creating releases

    steps:
      # needed for the release template
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cifuzz_installer

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: cifuzz Release ${{ needs.version.outputs.version }}
          tag_name: ${{ needs.version.outputs.tag }}
          body_path: ./.github/release_template.md
          generate_release_notes: true
          files: cifuzz_installer_*
          fail_on_unmatched_files: true

  error_notification:
    name: Error Notification
    runs-on: ubuntu-latest
    # send a slack notification if one of the jobs in `needs` failed
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs: [version, installer, tag_container_image, create_release]
    steps:
      - name: Send error notification to slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C046LFH588L" # cifuzz-notifications channel
          slack-message: "RELEASE ERROR: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  slack_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [version, create_release]
    if: needs.version.outputs.published == 'true'
    steps:
      - name: Slack Markdown Converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        id: converter
        with:
          text: ${{ needs.version.outputs.notes }}

      - name: Send notification to slack release channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C03RCP31BML" # release channel
          #channel-id: "C05SM4Y2MSL" # release-test channel
          # you can use https://app.slack.com/block-kit-builder for designing the payload
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New CI Fuzz Release :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Version*: ${{ needs.version.outputs.version }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Downloads @ <https://github.com/CodeIntelligenceTesting/cifuzz/releases/tag/v${{ needs.version.outputs.version }}|GitHub>"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(steps.converter.outputs.text) }}
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  send-release-event:
    name: Datadog release tracking
    runs-on: ubuntu-latest
    needs: [version, create_release]
    if: needs.version.outputs.published == 'true'
    steps:
      - name: Send Release Event to datadog
        run: |
          curl -sX POST "https://api.datadoghq.eu/api/v1/events" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            --data-raw '{
              "title": "cifuzz has been released",
              "text": "%%% \ncifuzz has been released with version **${{ needs.version.outputs.version }}**\n %%%",
              "tags": [
                "repo:${{ github.repository }}",
                "project:cifuzz",
                "version:${{ needs.version.outputs.version }}"
              ]
            }'
