name: Installer Pipeline

on:
  merge_group:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Get next version number
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.next_version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate version number
        id: next_version
        uses: ./.github/actions/version

  installer:
    uses: ./.github/workflows/workflow_installer.yml
    needs: version
    permissions:
      actions: write # for uploading artifacts
    with:
      version: ${{ needs.version.outputs.version }}
      compatibility_check: "true"
